#!/bin/bash
#This script was ugly, now its not so ugly but still feel free to fix any errors
#Scripted to work with Ubuntu 15.10 and backwards
#Earlier versions on github doesn't work properly on 15.10

if [ "$#" -ne 2 ]; then
    echo "usage ./cmd target-rootfs path-to-target-toolchain-compiler"
    exit -1
fi

#passed args
ROOTFS=$1
TOOLCHAIN=$2

if [ -x $TOOLCHAIN ]; then
    echo "Passed valid toolchain"
    MACHINE=$($TOOLCHAIN -dumpmachine)
    DEB_MULTI_ARCH_MADNESS=$ROOTFS/usr/lib/$MACHINE
fi

INITIAL_DIR=$PWD

function adjustSymLinks
{
    echo "Adjusting the symlinks in $1 to be relative"
    cd $1

    find . -maxdepth 1 -type l | while read i;
    do qualifies=$(file $i | sed -e "s/.*symbolic link to \(.*\)/\1/g" | grep ^/)
	
	if [ -n "$qualifies" ]; then
	    	newPath=$(file $i | sed -e "s/.*symbolic link to \(.*\)/\1/g" | sed -e "s,^/\(.*\),$2/\1,1");
		echo "Removing symbolic link $i ..." 	    	
		sudo rm $i;
		echo "Placing new symbolic link $i to $newPath ..."
		sudo ln -s $newPath $i;
	fi

    done	
    cd $INITIAL_DIR
}

adjustSymLinks $ROOTFS/usr/lib "../.."

echo "Testing for existence of potential debian multi-arch dir: $DEB_MULTI_ARCH_MADNESS"

if [ -n "$DEB_MULTI_ARCH_MADNESS" -a -e "$DEB_MULTI_ARCH_MADNESS" ]; then
    echo "Debian multiarch dir exists, adjusting"
    adjustSymLinks $DEB_MULTI_ARCH_MADNESS "../../.."
fi
